### ISSUE TITLE
segmentation violation for resourceGithubRepositoryEnvironmentRead using `app_auth`

### ISSUE THREAD

**Issue by mbarany** [integrations/terraform-provider-github#1146]
### Terraform Version
```bash
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/integrations/github v4.20.0
```

### Affected Resource(s)
- github_repository_environment

### Terraform Configuration Files
```hcl
resource "github_repository_environment" "environment" {
  for_each    = var.environments
  environment = each.key
  repository  = github_repository.repository.name
  wait_timer  = each.value.wait_timer_in_minutes != null ? each.value.wait_timer_in_minutes : 0

  reviewers {
    teams = each.value.approval_team_ids != null ? each.value.approval_team_ids : []
  }

  deployment_branch_policy {
    protected_branches     = each.value.protected_branches != null ? each.value.protected_branches : false
    custom_branch_policies = each.value.custom_branch_policies != null ? each.value.custom_branch_policies : false
  }
}
```

### Panic Output
```
Stack trace from the terraform-provider-github_v4.20.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xdaec5a]

goroutine 844 [running]:
github.com/terraform-providers/terraform-provider-github/github.resourceGithubRepositoryEnvironmentRead(0xc0001b8a10, 0xe481e0, 0xc0006640c0, 0xc0001b8a10, 0x0)
	github.com/terraform-providers/terraform-provider-github/github/resource_github_repository_environment.go:128 +0x4fa
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0001a7a80, 0xc000225c70, 0xe481e0, 0xc0006640c0, 0xc00055cca8, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/helper/schema/resource.go:455 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00011cb68, 0x119f150, 0xc0004f5aa0, 0xc000225b80, 0xc00011cb68, 0xc0004f5aa0, 0xc0002ada50)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0xfc7ee0, 0xc00011cb68, 0x119f150, 0xc0004f5aa0, 0xc0002436e0, 0x0, 0x119f150, 0xc0004f5aa0, 0xc0000b8300, 0xfc)
	github.com/hashicorp/terraform-plugin-sdk@v1.7.0/internal/tfplugin5/tfplugin5.pb.go:3153 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000156000, 0x11a6a78, 0xc000121b00, 0xc00041f100, 0xc0004f44b0, 0x17274d0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:995 +0x482
google.golang.org/grpc.(*Server).handleStream(0xc000156000, 0x11a6a78, 0xc000121b00, 0xc00041f100, 0x0)
	google.golang.org/grpc@v1.23.0/server.go:1275 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000036200, 0xc000156000, 0x11a6a78, 0xc000121b00, 0xc00041f100)
	google.golang.org/grpc@v1.23.0/server.go:710 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.23.0/server.go:708 +0xa5

Error: The terraform-provider-github_v4.20.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Important Factoids
This only seems to happen when I have this resource already in my state and only using `app_auth`

**Comment by mbarany** [comment]
actually this looks like a dup of https://github.com/integrations/terraform-provider-github/issues/1025

**Comment by mbarany** [comment]
I also tried on `4.23.0` and `4.24.1` and getting the same error

**Comment by eucleciojosias** [comment]
Same error here

**Comment by courentin** [comment]
I had the same issue, on my side granting a read-only permission on repository Actions to my Github app fixed the issue
