### ISSUE TITLE
[BUG] github_actions_runner_group: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cwthrivent** [integrations/terraform-provider-github#1524]
It seems that the `github_actions_runner_group` `resource` and the `github_repository` `data` source types have memory errors starting on provider version `v5.15.0`. This issue is *not* present on `v5.14.0` and earlier.

Copying logs from my comment from #1485 here:

```hcl
resource "github_actions_runner_group" "beta_linux_runners" {
  name       = "beta-linux-runners"
  visibility = "all"
}
```

<details>
<summary>Error message (Terraform v1.3.0, provider v5.16.0)</summary>

```
Terraform v1.3.0
on linux_amd64
Initializing plugins and modules...

...

│ Error: Plugin did not respond
│ 
│   with github_actions_runner_group.beta_linux_runners,
│   on github-thrivent.tf line 19, in resource "github_actions_runner_group" "beta_linux_runners":
│   19: resource "github_actions_runner_group" "beta_linux_runners" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.

...
```
</details>

<details>
<summary>Stack trace</summary>

```
Stack trace from the terraform-provider-github_v5.16.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xde71cd]

goroutine 65 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubActionsRunnerGroupRead(0xc000518540, {0xeb2f80?, 0xc0005c6400?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_actions_runner_group.go:188 +0x82d
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000149400, 0xc000590370, {0xeb2f80, 0xc0005c6400})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00011e8a8, {0xc000114600?, 0x4b86c6?}, 0xc000114600)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x105cba0?, 0xc00011e8a8}, {0x12c5730, 0xc000536270}, 0xc0001145a0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002ac380, {0x12c8e80, 0xc00048e1a0}, 0xc0005f0000, 0xc0002aeea0, 0x19845b0, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0002ac380, {0x12c8e80, 0xc00048e1a0}, 0xc0005f0000, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xde71cd]

goroutine 41 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubActionsRunnerGroupRead(0xc0000c9570, {0xeb2f80?, 0xc0001bcc40?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_actions_runner_group.go:188 +0x82d
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000536e60, 0xc00086a2d0, {0xeb2f80, 0xc0001bcc40})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0001150b8, {0xc00084c120?, 0x4b8746?}, 0xc00084c120)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x105cba0?, 0xc0001150b8}, {0x12c5730, 0xc00084ec60}, 0xc00084c0c0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000230a80, {0x12c8e80, 0xc000118820}, 0xc00015c480, 0xc000371350, 0x19845b0, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc000230a80, {0x12c8e80, 0xc000118820}, 0xc00015c480, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xde71cd]

goroutine 23 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubActionsRunnerGroupRead(0xc00013e690, {0xeb2f80?, 0xc00028e340?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_actions_runner_group.go:188 +0x82d
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000143d60, 0xc000735900, {0xeb2f80, 0xc00028e340})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00011a920, {0xc00073e2a0?, 0x4b86c6?}, 0xc00073e2a0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x105cba0?, 0xc00011a920}, {0x12c5730, 0xc000768540}, 0xc00073e240, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001fe380, {0x12c8e80, 0xc00030eb60}, 0xc000210a20, 0xc000435230, 0x19845b0, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0001fe380, {0x12c8e80, 0xc00030eb60}, 0xc000210a20, 0x0)
	google.golang.org/grpc@v1.46.2/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.46.2/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.46.2/server.go:920 +0x28a

Error: The terraform-provider-github_v5.16.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
</details>

**Comment by dbg-raghulkrishna** [comment]
i am also having this issue

**Comment by kfcampbell** [comment]
@cwthrivent thanks for catching this! The diff between v5.15.0 and v5.14.0 is [here](https://github.com/integrations/terraform-provider-github/compare/v5.14.0...v5.15.0). Is there anything suspicious in there to you?

**Comment by aq17** [comment]
Hi all, one of our users of our Pulumi bridged provider is also hitting this and is unable to refresh this resource
- https://github.com/pulumi/pulumi-github/issues/323
Is there an ETA or idea of when this may be fixed?

**Comment by kfcampbell** [comment]
That's obnoxious. I'm not seeing anything obvious in the diff...the data source for repositories doesn't look like it was touched at all during those versions.
