### ISSUE TITLE
[BUG] github_repository_environment crashes the plugin when using app authentication

### ISSUE THREAD

**Issue by audunsolemdal** [integrations/terraform-provider-github#1576]
Terraform version: 1.3.9
Github provider version: 5.18.0

The issue only occurs when using Github app Authentication. The github app is installed as a organization managed github app.
The resources are already created by using PAT (github_token) authentication. I am trying to replace the usage of PAT with github_app as much as possible.

The github app does have read/write permissions on `Environments` and `Administration` among other things.

If the `github_repository_environment` resource is removed, the plugin does not crash on the next run.

config:

```HCL
provider "github" {
  owner          = "myorg"

  app_auth {
    # env vars set in github actions workflows
  }
}


resource "github_repository_environment" "env" {
  environment = "myenvi"
  repository  = "myrepo"
  reviewers {
    teams = ["myteamid"]
  }
}


```

```
Stack trace from the terraform-provider-github_v5.18.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0xf432d0]

goroutine 415 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0xc0002ef3b0, {0xfe4d20?, 0xc0008e4000?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:137 +0x4b0
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003a1c20, 0xc000891400, {0xfe4d20, 0xc0008e4000})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000119240, {0xc0009608a0?, 0x4b8786?}, 0xc0009608a0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x11d3d80?, 0xc000119240}, {0x156d400, 0xc000985ec0}, 0xc0002eeee0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x1570fc8, 0xc0005cf6c0}, 0xc00092e5a0, 0xc0005e7020, 0x1d4edb0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x1570fc8, 0xc0005cf6c0}, 0xc00092e5a0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:[1713](https://github.com/myorg/myrepo/actions/runs/4315239488/jobs/7529334243#step:11:1714) +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-github_v5.18.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by SizZiKe** [comment]
@audunsolemdal  #840 is related, add actions.read to your app.
Still a bug though!
