### ISSUE TITLE
[BUG]: nil pointer panic on github_repository_environment when using GitHub PAT

### ISSUE THREAD

**Issue by BenHall-1** [integrations/terraform-provider-github#1661]
### Describe the need

Getting a nill pointer panic when trying to use github_repository_environment in Terraform Cloud via a GitHub PAT

### SDK Version

terraform-provider-github v5.23.0

### API Version

N/A

### Relevant log output

```shell
Stack trace from the terraform-provider-github_v5.23.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xfa4350]

goroutine 91 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0xc000364620, {0x1049ee0?, 0xc000285a40?})
github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:137 +0x4b0
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000406c80, 0xc000342870, {0x1049ee0, 0xc000285a40})
github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000e890, {0xc00034a4e0?, 0x4b8786?}, 0xc00034a4e0)
github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x12437c0?, 0xc00000e890}, {0x15e9280, 0xc00084c210}, 0xc000364070, 0x0)
github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000588000, {0x15ed148, 0xc000601380}, 0xc000a4c6c0, 0xc0004932f0, 0x1e095d0, 0x0)
google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc000588000, {0x15ed148, 0xc000601380}, 0xc000a4c6c0, 0x0)
google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-github_v5.23.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BenHall-1** [comment]
I marked this as maintenance instead of bug by accident if someone could change that :)

**Comment by kfcampbell** [comment]
Can you provide the minimal amount of HCL that reproduces this issue?

**Comment by davidcorrigan714** [comment]
Pretty sure this is breaking us too. Just created a `github_repository_environment` and now all our runs are erroring trying to read the created resource. I think the run that created it was 5.23. Need to unblock our stuff then I can try to reproduce in a more controlled setup.

**Comment by gintautassulskus** [comment]
> Can you provide the minimal amount of HCL that reproduces this issue?

Here's HCL with GitHub application integration that I was unable to run due to the same bug: https://github.com/gintautassulskus/tf_gg_env_bug

**Comment by erictg** [comment]
I just got this error using app auth. It actually created the environment though. Here's a minimal reproduction of the HCL

```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"
      version = "5.25.0"
    }
}

provider "github" {
  owner = "REDACTED"
  app_auth {
    id              = var.gh_app_id
    installation_id = var.gh_install_id
    pem_file        = file(var.gh_pem_location)
  }
}

data "github_repository" "repo" {
  full_name = "REDACTED/REDACTED"
}

resource "github_repository_environment" "env" {
  environment = "REDACTED"
  repository  = data.github_repository.repo.name
  reviewers {
    users = var.reviewers
  }
  deployment_branch_policy {
    protected_branches     = true
    custom_branch_policies = false
  }
}
```

Here's the crash output:
```
│ Error: Plugin did not respond
│ 
│   with github_repository_environment.env,
│   on main.tf line 11, in resource "github_repository_environment" "env":
│   11: resource "github_repository_environment" "env" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-github_v5.25.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x80 pc=0x10144bf9c]

goroutine 69 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0x140007c7c00, {0x101850e40?, 0x1400066a100?})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:137 +0x3ec
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentCreate(0x1018e4d00?, {0x101850e40?, 0x1400066a100})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:107 +0x22c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x1400025cc80, 0x140007f8a50, 0x140008215c0, {0x101850e40, 0x1400066a100})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x3e0
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x140000b4a00, 0x140005c58a0, 0x10147ad29?, 0xf?)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x14000286690, {0x140007c7650?, 0x0?}, 0x140007c7650)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x6b8
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x101a4ba80?, 0x14000286690}, {0x101aa7950, 0x140007fd020}, 0x140007c75e0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000154000, {0x101aab7c8, 0x14000295040}, 0x14000a00c60, 0x140001d9320, 0x1022a56e0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x14000154000, {0x101aab7c8, 0x14000295040}, 0x14000a00c60, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x298

Error: The terraform-provider-github_v5.25.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by gintautassulskus** [comment]
Would anyone happen to know a workaround in the meantime?

I don't have experience with golang, but happy to pair on the problem if anyone is up for it.

**Comment by erictg** [comment]
@gintautassulskus creating secrets worked with no issue. My workaround was manually creating the environment for now and then referencing it by name until this is fixed.

**Comment by gintautassulskus** [comment]
> @gintautassulskus creating secrets worked with no issue. My workaround was manually creating the environment for now and then referencing it by name until this is fixed.

Thanks, sounds like a good approach.

**Comment by hco** [comment]
For me switching to a classic access token worked - fine grained failed.
