### ISSUE TITLE
[BUG]: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hamza3202** [integrations/terraform-provider-github#1719]
### Describe the need

The plugin is crashing

### SDK Version

v5.26.0

### Relevant log output

```shell
Stack trace from the terraform-provider-github_v5.26.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x80 pc=0x100bdebcc]

goroutine 121 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0x1400090bdc0, {0x100fe5620?, 0x140002bf0c0?})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:137 +0x3ec
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000565900, 0x14000a128c0, {0x100fe5620, 0x140002bf0c0})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1ac
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0x14000112950, {0x140004c7740?, 0x0?}, 0x140004c7740)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x338
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x1011e0be0?, 0x14000112950}, {0x10123d0a0, 0x1400087c720}, 0x1400090b9d0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002d0000, {0x101240f18, 0x140002bba00}, 0x1400086d320, 0x14000761860, 0x101a3d6b0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x140002d0000, {0x101240f18, 0x140002bba00}, 0x1400086d320, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x298

Error: The terraform-provider-github_v5.26.0 plugin crashed!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@hamza3202 can you provide a snippet of HCL that can reproduce this crash? What resource is it occurring on?

**Comment by hamza3202** [comment]
Unfortunately I no longer have the project in this state and its not possible for me to reproduce this.

**Comment by kfcampbell** [comment]
In that case, I'll close this and we can revisit if/when it happens again.
