### ISSUE TITLE
[BUG]: github_repository.pages.build_type change causes provider crash

### ISSUE THREAD

**Issue by benlangfeld** [integrations/terraform-provider-github#1724]
### Describe the need

I had a resource definition like the following:

```terraform
resource "github_repository" "repo" {
  name         = var.name

  dynamic "pages" {
    for_each = var.github_pages ? toset([1]) : toset([])
    content {
      source {
        branch = "gh-pages"
        path   = "/"
      }
    }
  }
}
```

after upgrading the provider version to v5.26.0, which included https://github.com/integrations/terraform-provider-github/pull/1663, I modified this accordingly to the following:

```terraform
resource "github_repository" "repo" {
  name         = var.name

  dynamic "pages" {
    for_each = var.github_pages ? toset([1]) : toset([])
    content {
      build_type = var.github_pages_actions ? "workflow" : "legacy"

      dynamic "source" {
        for_each = var.github_pages_actions ? toset([]) : toset([1])
        content {
          branch = "gh-pages"
          path   = "/"
        }
      }
    }
  }
}
```

I have one resource where `github_pages_actions` was set to `true`, and now `terraform apply` fails like so:

```
❯ terraform apply -target module.pac.module.github-repo.github_repository.repo -target module.ostruct-sanitizer.module.github-repo.github_repository.repo -target module.paperclip-eitheror.module.github-repo.github_repository.repo
module.ostruct-sanitizer.module.github-repo.github_repository.repo: Refreshing state... [id=ostruct-sanitizer]
module.pac.module.github-repo.github_repository.repo: Refreshing state... [id=pac]
module.paperclip-eitheror.module.github-repo.github_repository.repo: Refreshing state... [id=paperclip-eitheror]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.pac.module.github-repo.github_repository.repo will be updated in-place
  ~ resource "github_repository" "repo" {
        id                          = "pac"
        name                        = "pac"
        # (33 unchanged attributes hidden)

      ~ pages {
          + build_type = "workflow"
            # (4 unchanged attributes hidden)

          - source {
              - branch = "gh-pages" -> null
              - path   = "/" -> null
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.pac.module.github-repo.github_repository.repo: Modifying... [id=pac]
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify that no other changes are pending:
│     terraform plan
│ 
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error message.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.pac.module.github-repo.github_repository.repo,
│   on modules/github-repo/main.tf line 10, in resource "github_repository" "repo":
│   10: resource "github_repository" "repo" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-github_v5.26.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 53 [running]:
github.com/integrations/terraform-provider-github/v5/github.expandPagesUpdate({0x140007aa6c0?, 0x10579a991?, 0x3?})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository.go:860 +0x3c4
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryUpdate(0x140007a9110, {0x105b7d620?, 0x140009a0480})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository.go:726 +0x440
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0x14000712140, 0x14000ad4050, 0x140000a4600, {0x105b7d620, 0x140009a0480})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:326 +0x384
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0x1400013a180, 0x140003698a0, 0x14000352ab0?, 0x17?)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0x1400000e1f8, {0x140007a9570?, 0x0?}, 0x140007a9570)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x6b8
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x105d78be0?, 0x1400000e1f8}, {0x105dd50a0, 0x14000b10780}, 0x140007a9500, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000230000, {0x105dd8f18, 0x140006c2340}, 0x14000b12b40, 0x14000717b00, 0x1065d56e0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x14000230000, {0x105dd8f18, 0x140006c2340}, 0x14000b12b40, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x298

Error: The terraform-provider-github_v5.26.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0x46616c6b** [comment]
I already opened a PR with a fix:

- https://github.com/integrations/terraform-provider-github/pull/1716

**Comment by 0x46616c6b** [comment]
With the new release (5.28.0) the problem are solved. Can you confirm that?

**Comment by benlangfeld** [comment]
Yes, this seems to be fixed now. Thank you @0x46616c6b
