### ISSUE TITLE
[BUG]: Regression with Dependabot Organization secret since v5.27.0

### ISSUE THREAD

**Issue by frankywahl** [integrations/terraform-provider-github#1746]
Hi there,

There seems to be a regression introduced by version 5.28. My best understanding would be something relating to https://github.com/integrations/terraform-provider-github/pull/1718/files#diff-f746541448646d1732c2951600cb385e74f53f48d4d182d878c26d330ef04e0cR54 and how the go-github client moved over to using int64 as ids in v53.0.0

### Terraform Version
Terraform version: 1.5.0
Github Provider Version: v5.28.0 (Also happens in v5.27.0)

### Affected Resource(s)
- github_dependabot_organization_secret

### Panic Output
<details>
<summary> Stack Trace Output </summary>

```bash
panic: interface conversion: interface {} is int, not int64

goroutine 88 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubDependabotOrganizationSecretCreateOrUpdate(0x10e1be0?, {0x104dbe0?, 0xc00015c4c0?})
	github.com/integrations/terraform-provider-github/v5/github/resource_github_dependabot_organization_secret.go:104 +0x5ad
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000408500, 0xc000398be0, 0xc00078d0e0, {0x104dbe0, 0xc00015c4c0})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:326 +0x3e3
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00004bf80, 0xc0008498c8, 0x12a0d2c?, 0xf?)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000f248, {0xc0004795e0?, 0x4b8786?}, 0xc0004795e0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1248b80?, 0xc00000f248}, {0x15efd60, 0xc000780180}, 0xc000479570, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00013c000, {0x15f3c28, 0xc0001036c0}, 0xc0007379e0, 0xc00034d920, 0x1e156c0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc00013c000, {0x15f3c28, 0xc0001036c0}, 0xc0007379e0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-github_v5.28.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
</details>

### Expected Behavior
Succesful update

### Actual Behavior
Panic with provider 

### Steps to Reproduce
Create a `github_dependabot_organization_secret` with provider version v5.27.0+ 

<details>

<summary> Sample HCL </summary>

```hcl
terraform {
  required_providers {
    github = {
      source = "integrations/github"
      version = "5.27.0" # Also fails with v5.28.0
    }
  }
}

provider "github" {
  owner = var.owner
}

variable "owner" {
  type = string
}

resource "github_repository" "example" {
  name        = "example"
  description = "My awesome codebase"
  visibility = "public"
}

resource "github_dependabot_organization_secret" "example" {
  secret_name     = "example"
  visibility      = "selected"
  plaintext_value = "anything"
  selected_repository_ids = [
    github_repository.example.repo_id,
  ]
}
```
</details>

**Comment by kfcampbell** [comment]
Thank you for the excellent bug report! It looks like we're panicking [here](https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_dependabot_organization_secret.go#L104). @frankywahl is this something you have the inclination to open up a PR to fix?

**Comment by KenSpur** [comment]
I have noticed the int/int64 issue in working on the codespaces secrets aswel since i am building those on a copy of the Dependabot secrets.

changing
```go
selectedRepositoryIDs = append(selectedRepositoryIDs, id.(int64))
```
to

```
selectedRepositoryIDs = append(selectedRepositoryIDs, int64(id.(int))) 
```

Is how i fixt it for codespaces

**Comment by frankywahl** [comment]
Thanks for the feedback. I gave it a shot, but I think it needs an update in the go-github client. Doing what is suggested actually starts failing on the API request, because the API server is expecting a string (https://docs.github.com/en/rest/dependabot/secrets?apiVersion=2022-11-28#create-or-update-an-organization-secret) and not an array of integers anymore. When trying it with the suggested method above, I get the following: 

```bash
Invalid property /selected_repository_ids/0: `123456` is not of type `string`. []
╷
│ Error: PUT https://api.github.com/orgs/org/dependabot/secrets/example: 422 Invalid request.
│
│ Invalid property /selected_repository_ids/0: `123456` is not of type `string`. []
│
│   with github_dependabot_organization_secret.example,
│   on main.tf line 24, in resource "github_dependabot_organization_secret" "example":
│   24: resource "github_dependabot_organization_secret" "example" {
```

I will see if I have time to experiment with the go-github client and maybe file a bug report there if I can confirm that as being the issue.
