### ISSUE TITLE
[MAINT]: Seg fault around 'repo.TemplateRepository.Owner'

### ISSUE THREAD

**Issue by phyzical** [integrations/terraform-provider-github#1839]
### Describe the need

Basically we ran into an issue around one of the repositories (it is archived if that changes flow) we manage via terraform being based off of another repo that now 404s or its the fact the OWNER has been deleted

https://github.com/integrations/terraform-provider-github/blob/v5.25.1/github/resource_github_repository.go#L664

I am happy to submit a fix for this i was just hoping for a bit of guidance on the best way to solve this issue.

Would it be safe enough to assume that if there isnt an owner  also then we dont care? or should we let it keep going and just allow empty strings for  "owner":  "repository": ?

```
if repo.TemplateRepository != nil  && repo.TemplateRepository.Owner != nil  {
		d.Set("template", []interface{}{
			map[string]interface{}{
				"owner":      repo.TemplateRepository.Owner.Login,
				"repository": repo.TemplateRepository.Name,
			},
		})
	} else {
		d.Set("template", []interface{}{})
	}
```

### SDK Version

v5.25.1

### Relevant log output

```shell
Stack trace from the terraform-provider-github_v5.25.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104ac63cc]

goroutine 304 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryRead(0x140008667e0, {0x104ed5620?, 0x1400063a400?})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository.go:664 +0xe6c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000020640, 0x1400015cb40, {0x104ed5620, 0x1400063a400})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1ac
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0x14000306490, {0x14000190c00?, 0x0?}, 0x14000190c00)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x338
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x1050d0be0?, 0x14000306490}, {0x10512d070, 0x14000b16f60}, 0x14000866380, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002d2000, {0x105130ee8, 0x140006424e0}, 0x14000b24fc0, 0x140003ed320, 0x10592d6b0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xb90
google.golang.org/grpc.(*Server).handleStream(0x140002d2000, {0x105130ee8, 0x140006424e0}, 0x14000b24fc0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x298

Error: The terraform-provider-github_v5.25.1 plugin crashed!
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
What do you mean by 

> Would it be safe enough to assume that if there isnt an owner also then we dont care?

Does that mean throw an error? I kinda think it would be reasonable to continue with a blank owner and log a warning of some sort. What do you think?

**Comment by phyzical** [comment]
Sorry what i was trying to say is should we just not return the template object at all if there isnt an owner (as i think the template name in this case may have been blank too)

Granted this was a stale repo for us and we just removed the offending repo and let the provider keep on churning.

But i agree a blank owner with a warning would do the job, i just wasn't sure of any side effects this might have caused.
