### ISSUE TITLE
[BUG]: SIGSEGV when github_repository_file is given a directory

### ISSUE THREAD

**Issue by bstrand-cai** [integrations/terraform-provider-github#1930]
### Expected Behavior

Ideally, something like a null-delimited (or configurably-delimited) list of entries in the directory, but definitely not `SIGSEGV`.

### Actual Behavior

```
$ terraform plan
data.github_repository_file.nonexistent: Reading...
data.github_repository_file.directory: Reading...
data.github_repository_file.file: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Request cancelled
│
│   with data.github_repository_file.file,
│   on main.tf line 1, in data "github_repository_file" "file":
│    1: data "github_repository_file" "file" {
│
│ The plugin.(*GRPCProvider).ReadDataSource request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with data.github_repository_file.nonexistent,
│   on nonexistent.tf line 1, in data "github_repository_file" "nonexistent":
│    1: data "github_repository_file" "nonexistent" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with data.github_repository_file.directory,
│   on sigsegv.tf line 1, in data "github_repository_file" "directory":
│    1: data "github_repository_file" "directory" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-github_v5.39.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf2bd52]

goroutine 53 [running]:
github.com/google/go-github/v55/github.(*RepositoryContent).GetContent(0xc000688e10?)
        github.com/google/go-github/v55@v55.0.0/github/repos_contents.go:78 +0x12
github.com/integrations/terraform-provider-github/v5/github.dataSourceGithubRepositoryFileRead(0xc0005542a0, {0x10bbac0?, 0xc0007af8c0})
        github.com/integrations/terraform-provider-github/v5/github/data_source_github_repository_file.go:110 +0x692
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc000224820, 0xc00058c3c0, {0x10bbac0, 0xc0007af8c0})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:413 +0xc4
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000066e00, 0xc0005d39c0, 0x115fdc0?)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:451 +0x5e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc000784420, {0xc000558d40?, 0x4c3926?}, 0xc000558d40)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:1046 +0x2ad
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler({0x12ff540?, 0xc000784420}, {0x1718d90, 0xc000a9a390}, 0xc0005540e0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3341 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005c6000, {0x171e4b0, 0xc000102820}, 0xc000180480, 0xc0005c30b0, 0x2030d90, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1337 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0005c6000, {0x171e4b0, 0xc000102820}, 0xc000180480, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1714 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.55.0/server.go:959 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 16
        google.golang.org/grpc@v1.55.0/server.go:957 +0x165

Error: The terraform-provider-github_v5.39.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Version

```
$ terraform version
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/integrations/github v5.39.0
```

### Affected Resource(s)

`github_repository_file`

### Terraform Configuration Files

```hcl
# locals.tf
locals {
  repo   = "integrations/terraform-provider-github"
  branch = "main"
}

# main.tf
data "github_repository_file" "file" {
  repository = local.repo
  branch     = local.branch
  file       = ".go-version"
}

output "file" {
  value = data.github_repository_file.file.content
}

# nonexistent.tf
data "github_repository_file" "nonexistent" {
  repository = local.repo
  branch     = local.branch
  file       = "does-not-exist-random-86sduufl"
}

output "nonexistent" {
  value = data.github_repository_file.nonexistent.content
}

# providers.tf
provider "github" {
}

# sigsegv.tf
data "github_repository_file" "directory" {
  repository = local.repo
  branch     = local.branch
  file       = "vendor"
}

output "directory" {
  value = data.github_repository_file.directory.content
}

# versions.tf
terraform {
  required_version = "1.5.7"

  required_providers {
    github = {
      source  = "integrations/github"
      version = "5.39.0"
    }
  }
}
```

### Steps to Reproduce

Run `terraform plan` or `terraform apply` on the above file(s).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey thank you for hunting this down and apologies for the trouble.  I am going to assign the labels `hacktoberfest` and `Up for Grabs` to signal to the community that this is something that has been verified and can be worked. Please feel free to pick the issue up if you have time! Thank you again for all that you do for this community :heart: !
