### ISSUE TITLE
[BUG]: Provider repeatedly crashing while trying to apply membership changes

### ISSUE THREAD

**Issue by nfx** [integrations/terraform-provider-github#1931]
### Expected Behavior

no crashes

### Actual Behavior

there are many issues, leading to provider not being stable. 
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Request cancelled
│ 
│   with github_team.this["mosaic-maintain"],
│   on main.tf line 20, in resource "github_team" "this":
│   20: resource "github_team" "this" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
..
│ Error: Plugin did not respond
│ 
│   with github_team.this["tika-ocr-maintain"],
│   on main.tf line 20, in resource "github_team" "this":
│   20: resource "github_team" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
...
Stack trace from the terraform-provider-github_v5.39.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x80 pc=0x100dc9a4c]

goroutine 27 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0x1400063ea10, {0x101246fc0?, 0x140002b2bc0?})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:137 +0x40c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400021fea0, 0x14000179680, {0x101246fc0, 0x140002b2bc0})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x26c
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0x140005e2c50, {0x1400088c7e0?, 0x1400063e540?}, 0x1400088c7e0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x318
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x10148e940?, 0x140005e2c50}, {0x1014f3a58, 0x1400059bf20}, 0x1400063e540, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140006cc000, {0x1014f9170, 0x140006024e0}, 0x14000646000, 0x140006c5200, 0x101de4f90, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1337 +0xbe0
google.golang.org/grpc.(*Server).handleStream(0x140006cc000, {0x1014f9170, 0x140006024e0}, 0x14000646000, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1714 +0x7c4
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.55.0/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 51
        google.golang.org/grpc@v1.55.0/server.go:957 +0x154

Error: The terraform-provider-github_v5.39.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.75.0
+ provider registry.terraform.io/integrations/github v5.39.0

### Affected Resource(s)

- github_team
- github_team_members

### Terraform Configuration Files

```hcl
there are ~60 `github_team` instances


provider "github" {
  owner        = "XXX" # sometimes i also get an error that "XXX is a username, not an organization, but it's certainly an org
}

resource "github_team" "this" {
  for_each = local.members
  name     = each.key

  create_default_maintainer = false
}

resource "github_team_members" "this" {
  for_each = local.members
  team_id  = github_team.this[each.key].id
  dynamic "members" {
    for_each = each.value
    content {
      username = members.value
      role     = "member"
    }
  }
}

```
```


### Steps to Reproduce

terraform apply

### Debug Output

```shell
Once of concrete stack traces shows the lack of nil check for `env`: https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_repository_environment.go#L136-L138


panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x80 pc=0x100dc9a4c]

goroutine 27 [running]:
github.com/integrations/terraform-provider-github/v5/github.resourceGithubRepositoryEnvironmentRead(0x1400063ea10, {0x101246fc0?, 0x140002b2bc0?})
        github.com/integrations/terraform-provider-github/v5/github/resource_github_repository_environment.go:137 +0x40c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1400021fea0, 0x14000179680, {0x101246fc0, 0x140002b2bc0})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x26c
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0x140005e2c50, {0x1400088c7e0?, 0x1400063e540?}, 0x1400088c7e0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x318
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x10148e940?, 0x140005e2c50}, {0x1014f3a58, 0x1400059bf20}, 0x1400063e540, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140006cc000, {0x1014f9170, 0x140006024e0}, 0x14000646000, 0x140006c5200, 0x101de4f90, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1337 +0xbe0
google.golang.org/grpc.(*Server).handleStream(0x140006cc000, {0x1014f9170, 0x140006024e0}, 0x14000646000, 0x0)
        google.golang.org/grpc@v1.55.0/server.go:1714 +0x7c4
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.55.0/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 51
        google.golang.org/grpc@v1.55.0/server.go:957 +0x154

Error: The terraform-provider-github_v5.39.0 plugin crashed!
```

the reason is that error handling is not correct:
https://github.com/integrations/terraform-provider-github/blob/main/github/resource_github_repository_environment.go#L123-L132 - provider returns error only when a thing is not found, not any other errors.
```


### Panic Output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey thank you for hunting this down and apologies for the trouble.  I am going to assign the labels `hacktoberfest` and `Up for Grabs` to signal to the community that this is something that has been verified and can be worked. Please feel free to pick the issue up if you have time! Thank you again for all that you do for this community ❤️  !
